http:
  routers:
    router-api:
      rule: 'PathPrefixStrip(`/quality-dashboard/api`) && AddPrefix(`/api`)'
      service: quality-dashboard-server
    router-ui:
      rule: 'PathPrefixStrip(`/quality-dashboard`)'
      service: quality-dashboard-ui

  services:
    quality-dashboard-server:
      loadBalancer:
        servers:
          - url: http://server

    quality-dashboard-ui:
      loadBalancer:
        servers:
          - url: http://ui
