name: PR Check

on:
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Server
        run: |
          cd quality-dashboard-server
          npm ci
          npm run build
          npm run lint
          npm run test

      - name: Build UI
        run: |
          cd quality-dashboard-ui
          npm ci
          npm run build
          npm run lint
          npm run test

      - name: Build Docker Images
        run: |
          set -e
          chmod +x _dev/*.sh
          ./_dev/docker-build-images.sh

      - name: Start Test Environment
        run: |
          set -e
          chmod +x _dev/*.sh
          npm install -g pm2
          ./_dev/run-test-env.sh
          sleep 20

      - name: E2E Test
        uses: cypress-io/github-action@v4
        with:
          working-directory: tests/tests-e2e
          browser: chrome
